apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: rvps-reference-values
  namespace: trustee-operator-system
data:
  reference-values.json: |
      [
      ]

# No reference values yet
    # [
    #   {
    #     "name": "sample.svn",
    #     "expired": "2025-01-01T00:00:00Z",
    #     "hash-value": [
    #       {
    #         "alg": "sha256",
    #         "value": "1"
    #       }
    #     ]
    #   }
    # ]
